import { Providers } from "../redux/providers";
import UserAuth from "./auth/UserAuth";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="assets/vendors/mdi/css/materialdesignicons.min.css" />
      <link rel="stylesheet" href="assets/vendors/ti-icons/css/themify-icons.css" />
      <link rel="stylesheet" href="assets/vendors/css/vendor.bundle.base.css" />
      <link rel="stylesheet" href="assets/vendors/font-awesome/css/font-awesome.min.css" />
      <link rel="stylesheet" href="assets/vendors/font-awesome/css/font-awesome.min.css" />
      <link rel="stylesheet" href="assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css" />
      <link rel="stylesheet" href="assets/css/style.css" />
      <link rel="shortcut icon" href="assets/images/favicon.png" />
    </head>
        <body className={inter.className}>
          <Providers>
            <UserAuth />
            {children}
          </Providers>
        </body>
    </html>)

}
